import fs from "fs"
import path from "path"

export function buildSterkbouw({ repoRoot, log }) {
  log("[AO][BUILD] Start SterkBouw SaaS structuur")

  const structure = {
    backend: [
      "api/routes",
      "api/controllers",
      "api/middleware",
      "api/health.js",
      "server.js",
      "package.json"
    ],
    frontend: [
      "pages",
      "components",
      "styles",
      "lib/api.js",
      "pages/api/health.js",
      "package.json"
    ],
    executor: [
      "telegram",
      "ao_commands",
      "remap",
      "routes",
      "health.js"
    ]
  }

  Object.entries(structure).forEach(([module, paths]) => {
    const base = path.join(repoRoot, module)
    if (!fs.existsSync(base)) {
      fs.mkdirSync(base, { recursive: true })
      log(`[AO][BUILD] map aangemaakt: ${module}`)
    }

    paths.forEach(p => {
      const full = path.join(base, p)
      const dir = path.dirname(full)

      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })

      if (!fs.existsSync(full)) {
        fs.writeFileSync(full, defaultContent(p))
        log(`[AO][BUILD] bestand aangemaakt: ${module}/${p}`)
      }
    })
  })

  log("[AO][BUILD] Structuur klaar")
}

function defaultContent(file) {
  if (file.includes("health")) {
    return `export default function handler(req, res) {
  res.json({ ok: true, service: "sterkbouw" })
}`
  }

  if (file === "server.js") {
    return `import express from "express"
const app = express()
app.get("/health", (req, res) => res.json({ ok: true }))
app.listen(process.env.PORT || 3000)`
  }

  if (file === "package.json") {
    return JSON.stringify({
      name: "sterkbouw",
      version: "1.0.0",
      private: true
    }, null, 2)
  }

  return "// auto-generated by AO"
}
